"""Only including necessary changes to telemetry

Revision ID: 6964ab93cc69
Revises: ad01b5d8ac99
Create Date: 2026-04-12 17:27:21.736229

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6964ab93cc69'
down_revision: Union[str, Sequence[str], None] = 'ad01b5d8ac99'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('telemetry', sa.Column('net_power', sa.SmallInteger(), nullable=True))
    op.drop_column('telemetry', 'battery_temp')
    op.drop_column('telemetry', 'power_consumption')
    op.drop_column('telemetry', 'solar_power')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('telemetry', sa.Column('solar_power', sa.SMALLINT(), autoincrement=False, nullable=True))
    op.add_column('telemetry', sa.Column('power_consumption', sa.SMALLINT(), autoincrement=False, nullable=True))
    op.add_column('telemetry', sa.Column('battery_temp', sa.SMALLINT(), autoincrement=False, nullable=True))
    op.drop_column('telemetry', 'net_power')
    # ### end Alembic commands ###
