"""initial tables

Revision ID: ad01b5d8ac99
Revises: 5006f6e0d6e8
Create Date: 2026-03-06 13:18:37.842150

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad01b5d8ac99'
down_revision: Union[str, Sequence[str], None] = '5006f6e0d6e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('telemetry',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('dateTime', sa.DateTime(), nullable=False),
    sa.Column('battery_level', sa.SmallInteger(), nullable=True),
    sa.Column('cpu_temp', sa.SmallInteger(), nullable=True),
    sa.Column('battery_temp', sa.SmallInteger(), nullable=True),
    sa.Column('distance_traveled', sa.SmallInteger(), nullable=True),
    sa.Column('solar_power', sa.SmallInteger(), nullable=True),
    sa.Column('power_consumption', sa.SmallInteger(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', 'dateTime')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('telemetry')
    op.drop_table('users')
    # ### end Alembic commands ###
